version: "3"
services:
  serve:
    build: 
      context: .
      dockerfile: serve.Dockerfile
    ports:
      - 3005:3005
  nginx:
    build: 
      context: .
      dockerfile: nginx.Dockerfile
    ports:
      - 3000:80
  router:
    build: 
      context: .
      dockerfile: router.Dockerfile
    ports:
      - 3000:80
  oss:
    build:
      context: .
      dockerfile: oss.Dockerfile
      args:
        # 此处默认从宿主机(host)环境变量中传参，在宿主机中需要提前配置 ACCESS_KEY_ID/ACCESS_KEY_SECRET 环境变量
        - ACCESS_KEY_ID
        - ACCESS_KEY_SECRET
        - ENDPOINT=oss-cn-shanghai.aliyuncs.com
    ports:
      - 3000:80